name = "GithubMarkdown"
uuid = "ecb7cac2-dae3-4a6f-a5f6-8274be99c6cb"
authors = ["Sebastian Pfitzner"]
version = "0.2.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
gfm_jll = "1709ae2f-740e-5434-a713-d92bde733aaf"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
